import { backgroundTile } from './variables';
import foreground from './foreground.json';
import bigBackground from './assets/maps/houses_2_background.json';
import bigForeground from './assets/maps/houses_2_foreground.json';

const {
  grass,
  grassAlt,
  grassAlt2,
  dirtyGrass,
  greenFlower,
  redFlower,
  woodPlank,
  brick,
  waterTopRightCorner,
  waterRight,
  waterTopLeftCorner,
  waterLeft,
  waterTopRightDot,
  waterTop,
  waterTopLeftDot,
  water,
  waterBottomRightDot,
  waterBottom,
  waterBottomLeftDot,
  waterBottomLeftCorner,
  waterBottomRightCorner,
} = backgroundTile.list;

const padded4Water = array => {
  return [...Array(4).fill(water), ...array, ...Array(4).fill(water)];
};

const upperIsland = {
  tileList: [
    padded4Water([
      waterBottomRightDot,
      ...Array(17).fill(waterBottom),
      waterBottomLeftDot,
    ]),
    ...Array(17).fill(
      padded4Water(
        ...Array(17).fill([waterRight, ...Array(17).fill(grass), waterLeft]),
      ),
    ),
    padded4Water([
      waterTopRightDot,
      ...Array(7).fill(waterTop),
      woodPlank,
      ...Array(9).fill(waterTop),
      waterTopLeftDot,
    ]),
  ],
  tilePerRow: 27,
  tilePerColumn: 19,
  startPosition: {
    x: 16,
    y: 16,
  },
};

const centralIsland = {
  tileList: [
    padded4Water([
      ...Array(8).fill(water),
      woodPlank,
      ...Array(10).fill(water),
    ]),
    padded4Water([
      ...Array(8).fill(water),
      woodPlank,
      ...Array(10).fill(water),
    ]),
    padded4Water([
      water,
      water,
      waterBottomRightDot,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottom,
      woodPlank,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottom,
      waterBottomLeftDot,
      water,
    ]),
    padded4Water([
      woodPlank,
      woodPlank,
      woodPlank,
      dirtyGrass,
      grass,
      grass,
      grass,
      grass,
      dirtyGrass,
      grassAlt,
      grass,
      grass,
      grassAlt2,
      grass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      dirtyGrass,
      grass,
      grass,
      grass,
      grass,
      dirtyGrass,
      grass,
      grass,
      grass,
      grass,
      grass,
      greenFlower,
      greenFlower,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      dirtyGrass,
      grass,
      grass,
      grass,
      grass,
      dirtyGrass,
      grass,
      grass,
      grass,
      grass,
      grass,
      greenFlower,
      redFlower,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      dirtyGrass,
      grass,
      grass,
      grass,
      grass,
      dirtyGrass,
      grass,
      grass,
      grass,
      grassAlt,
      grass,
      grassAlt,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      dirtyGrass,
      grass,
      grassAlt,
      grass,
      grass,
      dirtyGrass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      grass,
      grass,
      dirtyGrass,
      waterTopLeftCorner,
      waterTopRightCorner,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      grass,
      grass,
      dirtyGrass,
      grass,
      grassAlt,
      dirtyGrass,
      waterBottomLeftCorner,
      waterBottomRightCorner,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      grass,
      grass,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      dirtyGrass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      grassAlt2,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grassAlt,
      dirtyGrass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      dirtyGrass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      grass,
      grass,
      grass,
      grass,
      grass,
      grass,
      grassAlt2,
      grass,
      grass,
      grass,
      dirtyGrass,
      grass,
      grass,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      grass,
      grass,
      grass,
      grass,
      grassAlt,
      grass,
      grass,
      grass,
      grass,
      grass,
      dirtyGrass,
      grass,
      grassAlt,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterRight,
      grass,
      grass,
      grass,
      grass,
      grassAlt,
      grass,
      grass,
      grass,
      grass,
      grass,
      dirtyGrass,
      grass,
      grassAlt,
      grass,
      waterLeft,
      water,
    ]),
    padded4Water([
      water,
      water,
      waterTopRightDot,
      waterTop,
      waterTop,
      waterTop,
      waterTop,
      waterTop,
      waterTop,
      waterTop,
      waterTop,
      waterTop,
      waterTop,
      woodPlank,
      waterTop,
      waterTop,
      waterTop,
      waterTopLeftDot,
      water,
    ]),
    padded4Water([
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      woodPlank,
      water,
      water,
      water,
      water,
      water,
    ]),
    padded4Water([
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      water,
      woodPlank,
      water,
      water,
      water,
      water,
      water,
    ]),
  ],
  startPosition: {
    x: 48,
    y: 48,
  },
  tilePerRow: 27,
  tilePerColumn: 19,
};

const map = {
  tileList: [
    ...Array(4).fill(Array(27).fill(water)),
    ...upperIsland.tileList,
    ...centralIsland.tileList,
    ...Array(4).fill(Array(27).fill(water)),
  ],
  startPosition: {
    x: 216,
    y: 524,
  },
  tilePerRow: 27,
  tilePerColumn: 46,
};

export { map };

const foregroundMap = {
  tileList: foreground,
  startPosition: {
    x: 288,
    y: 157,
  },
  tilePerRow: 72,
  tilePerColumn: 36,
};

// export default foregroundMap;
export const background = bigBackground;

export default bigForeground;
