import tileSrc from './assets/tiles.png';
import playerSrc from './assets/sacha.png';
import pikachuSrc from './assets/pikachu.png';
import pkmnSrc from './assets/pkmn.png';
import melofeeSrc from './assets/melofee.png';
import jessieSrc from './assets/jessie.png';
import jamesSrc from './assets/james.png';

export const layer = {
  floor: 0,
  player: 1,
  obstacle: 2,
  tpIn: 3,
  tpOut: 4,
  jump: 5,
};

export const backgroundTile = {
  height: 16,
  width: 16,
  src: tileSrc,
  tilePerRow: 8,
  list: {
    grass: { layer: layer.floor, id: 0 },
    grassAlt: { layer: layer.floor, id: 1 },
    grassAlt2: { layer: layer.floor, id: 2 },
    dirtyGrass: { layer: layer.floor, id: 3 },
    greenFlower: { layer: layer.floor, id: 4 },
    redFlower: { layer: layer.floor, id: 5 },
    woodPlank: { layer: layer.floor, id: 6 },
    brick: { layer: layer.floor, id: 7 },
    waterBottom: { layer: layer.obstacle, ids: [8, 24, 40, 56, 8] },
    waterLeft: { layer: layer.obstacle, ids: [9, 25, 41, 57, 9] },
    waterTopLeftCorner: { layer: layer.obstacle, ids: [10, 26, 42, 58, 10] },
    waterTopRightCorner: { layer: layer.obstacle, ids: [11, 27, 43, 59, 11] },
    waterBottomRightDot: { layer: layer.obstacle, ids: [12, 28, 44, 60, 12] },
    waterBottomLeftDot: { layer: layer.obstacle, ids: [13, 29, 45, 61, 13] },
    water: { layer: layer.obstacle, ids: [14, 30, 46, 62, 14] },
    waterBridgeLeft: { layer: layer.obstacle, ids: [15, 31, 47, 63, 15] },
    waterRight: { layer: layer.obstacle, ids: [16, 32, 48, 64, 16] },
    waterTop: { layer: layer.obstacle, ids: [17, 33, 49, 65, 17] },
    waterBottomLeftCorner: { layer: layer.obstacle, ids: [18, 34, 50, 66, 18] },
    waterBottomRightCorner: {
      layer: layer.obstacle,
      ids: [19, 35, 51, 67, 19],
    },
    waterTopRightDot: {
      layer: layer.obstacle,
      ids: [20, 36, 52, 68, 20],
    },
    waterTopLeftDot: { layer: layer.obstacle, ids: [21, 37, 53, 69, 21] },
    waterBridge: { layer: layer.obstacle, ids: [22, 38, 54, 70, 22] },
    waterBridgeRight: { layer: layer.obstacle, ids: [23, 39, 55, 71, 23] },
    roofEndLeft: { layer: layer.obstacle, id: 72 },
    roofEnd: { layer: layer.obstacle, id: 73 },
    roofEndRight: { layer: layer.obstacle, id: 74 },
    roofStartEnd: { layer: layer.obstacle, id: 75 },
    roof: { layer: layer.obstacle, id: 76 },
    roofStartEndLeft: { layer: layer.obstacle, id: 77 },
    roofStartLeft: { layer: layer.obstacle, id: 80 },
    roofStart: { layer: layer.obstacle, id: 81 },
    roofStartRight: { layer: layer.obstacle, id: 82 },
    door: { layer: layer.obstacle, id: 83 },
    roofLeft: { layer: layer.obstacle, id: 84 },
    roofStartEndRight: { layer: layer.floor, id: 85 },
    roofedWallLeftEnd: { layer: layer.obstacle, id: 88 },
    wallSimple: { layer: layer.obstacle, id: 89 },
    roofedWallRightEnd: { layer: layer.obstacle, id: 90 },
    wallStriped: { layer: layer.obstacle, id: 91 },
    roofRight: { layer: layer.obstacle, id: 92 },
    wallStripedRightEnd: { layer: layer.obstacle, id: 93 },
    highRoofedWallLeftEnd: { layer: layer.obstacle, id: 94 },
    highWallDoubleWindow: { layer: layer.obstacle, id: 95 },
    wallStripedDoubleWindow: { layer: layer.obstacle, id: 96 },
    wallSimpleRightWindow: { layer: layer.obstacle, id: 97 },
    wallSimpleLeftWindow: { layer: layer.obstacle, id: 98 },
    wallStripedLeftWindow: { layer: layer.obstacle, id: 99 },
    wallStripedRightWindow: { layer: layer.obstacle, id: 100 },
    wallStripedLeftEnd: { layer: layer.obstacle, id: 101 },
    highWall: { layer: layer.obstacle, id: 102 },
    highRoofedWallRightEnd: { layer: layer.obstacle, id: 103 },
    roofedFloorLeftEnd: { layer: layer.obstacle, id: 104 },
    floorLeftWindow: { layer: layer.obstacle, id: 105 },
    floorRightWindow: { layer: layer.obstacle, id: 106 },
    floorDoubleWindow: { layer: layer.obstacle, id: 107 },
    floor: { layer: layer.obstacle, id: 108 },
    roofedFloorRightEnd: { layer: layer.obstacle, id: 109 },
    highWallLeftWindow: { layer: layer.obstacle, id: 110 },
    highWallRightWindow: { layer: layer.obstacle, id: 111 },
    flatRoofLeftEnd: { layer: layer.obstacle, id: 112 },
    flatRoofEnd: { layer: layer.obstacle, id: 113 },
    flatRoofRightEnd: { layer: layer.obstacle, id: 114 },
    highRoofedWallLeft: { layer: layer.obstacle, id: 115 },
    highRoofedWall: { layer: layer.obstacle, id: 116 },
    highRoofedWallRight: { layer: layer.obstacle, id: 117 },
    highWallLeftEnd: { layer: layer.obstacle, id: 118 },
    highWallRightEnd: { layer: layer.obstacle, id: 119 },
    flatRoofLeft: { layer: layer.obstacle, id: 120 },
    flatRoof: { layer: layer.obstacle, id: 121 },
    flatRoofRight: { layer: layer.obstacle, id: 122 },
    flatRoof2LeftEnd: { layer: layer.obstacle, id: 123 },
    flatRoof2End: { layer: layer.obstacle, id: 124 },
    flatRoof2RightEnd: { layer: layer.obstacle, id: 125 },
    flatRoof2LeftStart: { layer: layer.obstacle, id: 126 },
    flatRoof2RightStart: { layer: layer.obstacle, id: 127 },
    flatRoofLeftStart: { layer: layer.obstacle, id: 128 },
    flatRoofStart: { layer: layer.obstacle, id: 129 },
    flatRoofRightStart: { layer: layer.obstacle, id: 130 },
    flatRoof2Left: { layer: layer.obstacle, id: 131 },
    flatRoof2: { layer: layer.obstacle, id: 132 },
    flatRoof2Right: { layer: layer.obstacle, id: 133 },
    flatRoof2Start: { layer: layer.obstacle, id: 134 },
    brickedFloorWindowLeftEnd: { layer: layer.obstacle, id: 136 },
    brickedFloorDoubleWindow: { layer: layer.obstacle, id: 137 },
    brickedFloorWindowRightEnd: { layer: layer.obstacle, id: 138 },
    brickedFloorLeftEnd: { layer: layer.obstacle, id: 139 },
    brickedFloor: { layer: layer.obstacle, id: 140 },
    brickedFloorLeftWindow: { layer: layer.obstacle, id: 141 },
    brickedFloorRightWindow: { layer: layer.obstacle, id: 142 },
    brickedFloorRightEnd: { layer: layer.obstacle, id: 143 },
    wallWindowLeftEnd: { layer: layer.obstacle, id: 144 },
    wallWindowRightEnd: { layer: layer.obstacle, id: 146 },
    brickedWallLeftEnd: { layer: layer.obstacle, id: 147 },
    brickedWall: { layer: layer.obstacle, id: 148 },
    brickedWallLeftWindow: { layer: layer.obstacle, id: 149 },
    brickedWallRightWindow: { layer: layer.obstacle, id: 150 },
    pathDelimiter1: { layer: layer.obstacle, id: 151 },
    pathDelimiter2: { layer: layer.floor, id: 152 },
    pathDelimiter3: { layer: layer.floor, id: 153 },
    pathDelimiter4: { layer: layer.floor, id: 154 },
    pathDelimiter5: { layer: layer.floor, id: 155 },
    pathDelimiter6: { layer: layer.floor, id: 156 },
    pathDelimiter7: { layer: layer.floor, id: 157 },
    pathDelimiter8: { layer: layer.floor, id: 158 },
    tree: { layer: layer.obstacle, id: 159 },
    pathDelimiter9: { layer: layer.floor, id: 160 },
    pathDelimiter10: { layer: layer.floor, id: 161 },
    pathDelimiter11: { layer: layer.floor, id: 162 },
    pathDelimiter11b: { layer: layer.floor, id: 163 },
    pathDelimiter12: { layer: layer.floor, id: 164 },
    pathDelimiter13: { layer: layer.floor, id: 165 },
    pathDelimiter13b: { layer: layer.floor, id: 166 },
    tree2: { layer: layer.floor, id: 167 },
    pathDelimiter14: { layer: layer.floor, id: 168 },
    pathDelimiter15: { layer: layer.floor, id: 169 },
    pathDelimiter16: { layer: layer.floor, id: 170 },
    pathDelimiter17: { layer: layer.floor, id: 171 },
    pathDelimiter18: { layer: layer.floor, id: 172 },
    pathDelimiter19: { layer: layer.floor, id: 173 },
    whiteGround: { layer: layer.floor, id: 174 },
    block: { layer: layer.floor, id: 175 },
    topFlower: { layer: layer.obstacle, id: 176 },
    topBookShelf: { layer: layer.obstacle, id: 177 },
    topLeftTable: { layer: layer.obstacle, id: 178 },
    topRightTable: { layer: layer.obstacle, id: 179 },
    tv: { layer: layer.obstacle, id: 180 },
    computerStationTop: { layer: layer.obstacle, id: 181 },
    bedTop: { layer: layer.obstacle, id: 182 },
    chair: { layer: layer.floor, id: 183 },
    bottomFlower: { layer: layer.obstacle, id: 184 },
    bottomBookShelf: { layer: layer.obstacle, id: 185 },
    bottomLeftTable: { layer: layer.obstacle, id: 186 },
    bottomRightTable: { layer: layer.obstacle, id: 187 },
    snes: { layer: layer.floor, id: 188 },
    computerStationBottom: { layer: layer.obstacle, id: 189 },
    bedBottom: { layer: layer.obstacle, id: 190 },
    houseGround: { layer: layer.obstacle, id: 191 },
    shelfTop: { layer: layer.obstacle, id: 192 },
    houseWall: { layer: layer.obstacle, id: 193 },
    houseWallPainting: { layer: layer.obstacle, id: 194 },
    houseWallShutter: { layer: layer.obstacle, id: 195 },
    houseDoubleWindow: { layer: layer.obstacle, id: 196 },
    houseWindowRight: { layer: layer.obstacle, id: 197 },
    houseWindowLeft: { layer: layer.obstacle, id: 198 },
    chair2: { layer: layer.floor, id: 199 },
    shelfBottom: { layer: layer.obstacle, id: 200 },
    redCarpet: { layer: layer.floor, id: 201 },
    blueCarpet: { layer: layer.floor, id: 202 },
    greenCarpet: { layer: layer.floor, id: 203 },
    corneredTopLeftTable: { layer: layer.obstacle, id: 204 },
    pkmnTopLeftTable: { layer: layer.obstacle, id: 205 },
    pkmnTopRightTable: { layer: layer.obstacle, id: 206 },
    corneredTopRightTable: { layer: layer.obstacle, id: 207 },
    topLeftSofa: { layer: layer.obstacle, id: 208 },
    topSofa: { layer: layer.obstacle, id: 209 },
    topRightSofa: { layer: layer.obstacle, id: 210 },
    upStair: { layer: layer.floor, id: 211 },
    leftTable: { layer: layer.obstacle, id: 212 },
    pkmnLeftTable: { layer: layer.obstacle, id: 213 },
    pkmnRightTable: { layer: layer.obstacle, id: 214 },
    rightTable: { layer: layer.obstacle, id: 215 },
    bottomLeftSofa: { layer: layer.floor, id: 216 },
    bottomSofa: { layer: layer.floor, id: 217 },
    bottomRightSofa: { layer: layer.floor, id: 218 },
    downStair: { layer: layer.floor, id: 219 },
    corneredLeftTable2: { layer: layer.obstacle, id: 220 },
    table2: { layer: layer.obstacle, id: 221 },
    table2bis: { layer: layer.obstacle, id: 222 },
    corneredRightTable2: { layer: layer.obstacle, id: 223 },
    topLeftCoffeeTable3: { layer: layer.obstacle, id: 224 },
    topRightTable3: { layer: layer.obstacle, id: 225 },
    leftFruitTable3: { layer: layer.obstacle, id: 226 },
    rightFruitTable3: { layer: layer.obstacle, id: 227 },
    corneredBottomLeftTable2: { layer: layer.obstacle, id: 228 },
    bottomLeftTable2: { layer: layer.obstacle, id: 229 },
    bottomRightTable2: { layer: layer.floor, id: 230 },
    corneredBottomRightTable2: { layer: layer.floor, id: 231 },
    leftTable3: { layer: layer.obstacle, id: 232 },
    rightCoffeeTable3: { layer: layer.obstacle, id: 233 },
    bottomRightTable3: { layer: layer.obstacle, id: 234 },
    bottomLeftTable3: { layer: layer.obstacle, id: 235 },
    topBookTable: { layer: layer.obstacle, id: 236 },
    paintingHouseWall2: { layer: layer.obstacle, id: 237 },
    houseWall2: { layer: layer.obstacle, id: 238 },
    topBed2: { layer: layer.obstacle, id: 239 },
    topLeftDesk: { layer: layer.obstacle, id: 240 },
    topRightDesk: { layer: layer.obstacle, id: 241 },
    bottomRightDesk: { layer: layer.floor, id: 242 },
    bottomLeftDesk: { layer: layer.floor, id: 243 },
    bottomBookTable: { layer: layer.obstacle, id: 244 },
    scrollHouseWall2: { layer: layer.obstacle, id: 245 },
    trash: { layer: layer.obstacle, id: 246 },
    bed2Bottom: { layer: layer.obstacle, id: 247 },
    topLeftMountain: { layer: layer.obstacle, id: 248 },
    topEndMountain: { layer: layer.obstacle, id: 249 },
    topRightMountain: { layer: layer.obstacle, id: 250 },
    topLeftSmallTable: { layer: layer.obstacle, id: 251 },
    topRightSmallTable: { layer: layer.obstacle, id: 252 },
    topLeftFlowerTable: { layer: layer.obstacle, id: 253 },
    topRightFloweTable: { layer: layer.obstacle, id: 254 },
    boulder: { layer: layer.obstacle, id: 255 },
    leftMountain: { layer: layer.obstacle, id: 256 },
    topMountain: { layer: layer.obstacle, id: 257 },
    rightMountain: { layer: layer.obstacle, id: 258 },
    rightEndJump: { layer: layer.jump, id: 259 },
    pillar: { layer: layer.obstacle, id: 260 },
    leftEndJump: { layer: layer.jump, id: 261 },
    stairs: { layer: layer.floor, id: 262 },
    sign1: { layer: layer.obstacle, id: 263 },
    bottomLeftMountain: { layer: layer.obstacle, id: 264 },
    bottomMountain: { layer: layer.obstacle, id: 265 },
    bottomRightMountain: { layer: layer.obstacle, id: 266 },
    leftJump: { layer: layer.jump, id: 267 },
    halfWoodPlank: { layer: layer.floor, id: 268 },
    rightJump: { layer: layer.jump, id: 269 },
    pkmnHead: { layer: layer.obstacle, id: 270 },
    sign2: { layer: layer.obstacle, id: 271 },
    leftEntranceMountain: { layer: layer.obstacle, id: 272 },
    entranceMountain: { layer: layer.obstacle, id: 273 },
    rightEntranceMountain: { layer: layer.obstacle, id: 274 },
    bottomLeftCornerJump: { layer: layer.jump, id: 275 },
    bottomJump: { layer: layer.jump, id: 276 },
    bottomRightJump: { layer: layer.jump, id: 277 },
    pkmnBottom: { layer: layer.jump, id: 278 },
    cavernSign: { layer: layer.obstacle, id: 279 },
  },
};

export const canvas = {
  width: 432,
  height: 480,
  scale: 2,
};

export const playerTile = {
  height: 16,
  width: 16,
  src: playerSrc,
  pikachuSrc,
  pkmnSrc,
  melofeeSrc,
  jessieSrc,
  jamesSrc,
  layer: layer.player,
  pxPerFrameMovement: 1,
  idle: {
    up: 3,
    right: 6,
    down: 0,
    left: 9,
  },
  move: {
    down: 1,
    downAlt: 2,
    up: 4,
    upAlt: 5,
    right: 7,
    left: 10,
  },
  tilePerRow: 3,
  direction: {
    up: 0,
    down: 1,
    left: 2,
    right: 3,
  },
};

export const keyCodes = {
  up: 'ArrowUp',
  down: 'ArrowDown',
  right: 'ArrowRight',
  left: 'ArrowLeft',
};

export const MAP_STATUS_LOADING = 'loading';

export const MAP_STATUS_PLAYING = 'playing';

export const MAP_STATUS_INIT = 'initializing';
